version: "3.8"
services:
  crontab-master:
    build:
      context: master/main/
#    image: chia11/crontab-master
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - etcd
  crontab-worker:
    build:
      context: worker/main/
#    image: chia11/crontab-worker
    restart: always
    depends_on:
      - mongo
      - etcd
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  etcd:
    image: bitnami/etcd
    restart: always
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    ports:
      - "2379:2379"
      - "2380:2380"